### PR TITLE
feat: added portfolio section

### PR DESCRIPTION
**Pull request by amitanshusahu**
## Pc view 👇🏻 
image
## Tablet view 👇🏻 
image

# Note to reviewer:-
> __NOTE__ : 
> - kept the vertical gradient width 30px( same as margin ) so that it can only been seen when the cards overflow
> - the gradient width and height is fixed and set with reference to the card height , so if in future the card height changes the gradient height must be changed

### CODE REVIEW

**Comment by zeim839** [comment]
Hey, the three blocks should always be the same width and the right-most one should always be fading out - regardless of whether theyre on tablet or desktop screen sizes. Try adding two more blocks (total 5 blocks), the last two should be hidden by the scroll view. 

Also, could you show an arrow button so we can scroll left/right? When there are no more elements on the right, the fade-out effect should show up on the left.

**Comment by amitanshusahu** [comment]
Ok I get it...

**Comment by zeim839** [comment]
Thank you

**Comment by amitanshusahu** [comment]
# changes -
- [x] fixed width of the cards
- [x] created scroll buttons
- [x] implemented " show buttons if scrollable "
### preview 👇🏻 
[screen-recorder-wed-nov-02-2022-23-19-06.webm](https://user-images.githubusercontent.com/83657737/199566759-72a8a033-3862-4635-bdde-8b514b9f15fb.webm)

**Review by zeim839 — CHANGES_REQUESTED** [review]
Hey @amitanshusahu, great work. I've managed to center and align the elements to the middle of the page. Could you please edit the buttons so that they always appear on the left/right of the cards (instead of all the way to the left/right of the page)?

**Comment by amitanshusahu** [comment]
> Hey @amitanshusahu, great work. I've managed to center and align the elements to the middle of the page. Could you please edit the buttons so that they always appear on the left/right of the cards (instead of all the way to the left/right of the page)?

@zeim839 i don't get it could you please show some image or some thing ...

**Comment by zeim839** [comment]
sample

I hope this clears it up. Move the button so that it's always right next to the colored divs. 
@amitanshusahu

**Comment by amitanshusahu** [comment]
@zeim839 , fixed the slider buttons 
see preview 👇🏻 
[screen-recorder-sat-nov-05-2022-01-49-25.webm](https://user-images.githubusercontent.com/83657737/200069023-e8059445-b8d8-415c-b303-44aab5d90059.webm)

**Review by zeim839 — CHANGES_REQUESTED** [review]
Hey @amitanshusahu,
Please do not merge with main, this complicates the commit history and makes it harder for me to commit - I will update the branch myself once it's time to merge. I have also force pushed a commit that centers the portfolio section and fixes some merging issues. Likewise I renamed some of your CSS components. You will need to run `git fetch` and `git pull` on the branch to access it. Please make sure your local commit history looks like this before continuing:
Screenshot 2022-11-05 at 5 05 38 PM

Finally, the issue with the scroll buttons still persists on ultra-wide devices. Please check out this [guide](https://developer.chrome.com/docs/devtools/device-mode/) for testing responsive sites on google chrome - set the width to 1800px and you can check out the issue for yourself.

Here's a preview:
Screenshot 2022-11-05 at 5 02 34 PM

Amazing work though, lets get this issue out of the way; we're almost finished.

**Comment by amitanshusahu** [comment]
@zeim839 , sorry but i literally have no idea what you are saying "'don't merge the main" 😕 ,
however i followed what you said `git fetch` and `git pull`
here is the err it throws, i don't know what this is , a noob in git 😓 
image

**Comment by amitanshusahu** [comment]
@zeim839 , done 👍🏻  i cloned the branch again, everything is now fine and fixed 

- [x] fixed swipe btns on large screens

image

- [x] git history 👇🏻 

image

**Comment by zeim839** [comment]
Awesome, thanks.

**Review by zeim839 — APPROVED** [review]

**Pull request merged**
