### PR TITLE
fixed issue #95 - porfolio section fixed

### PR DESCRIPTION
**Pull request by adrianmarinwork**
I have fixed the problem with the porfolio section that wasn't scrolling correctly in smaller screens.
I have commented all the changes in the code for you to understand why those changes and how does the code work.
If you have any question or want to ask me something, don't hesitate to do it!

### CODE REVIEW

**Comment by zeim839** [comment]
@adrianmarinwork 
Please run `npm run fix` to automatically fix linting errors. The command might not fix all of them, In which case it'll list any remaining errors that you'll need to manually address. 

The linting command ensures that all our javascript code is written in the same style. 

Let me know if you need any help.

**Comment by adrianmarinwork** [comment]
When running the command, it's telling me that ResizeObserver is not defined but it's a native object of javascript.
Captura

**Comment by zeim839** [comment]
Add this comment to the top of the file:
```js
/* global ResizeObserver */
```

**Comment by adrianmarinwork** [comment]
Nice I have cleaned all the issues mentioned by the `npm run fix`, thank you!

**Review by zeim839 — APPROVED** [review]

**Pull request merged**
