### PR TITLE
Cache index

### PR DESCRIPTION
**Pull request by devp4**
Created callback to cache index page. 

For line 6 in callbacks.js, the function has an err (error) parameter. Not entirely sure how to write a better error handler for it.

### CODE REVIEW

**Comment by zeim839** [comment]
Could you add a function to the cache module that lets us force an update?

**Comment by devp4** [comment]
Yeah, by force an update do you mean forcefully call every callback?

**Comment by zeim839** [comment]
Yes

**Comment by devp4** [comment]
If there is a bug with the rate limiter, should I push it here or make a new PR?

**Comment by zeim839** [comment]
Make a separate PR please

**Review by zeim839 — APPROVED** [review]

**Pull request merged**
