### PR TITLE
Added box for About section on landing page

### PR DESCRIPTION
**Pull request by Brian-Magnuson**
image
Added the box shape for the about section in `index.ejs`. Added styling in `index.css`, including trapezoid reflection effect. Note: the box does stretch, but is not fully responsive; text alignment may break when the window becomes too narrow.

### CODE REVIEW

**Comment by zeim839** [comment]
Hey @Brian-Magnuson , could you also add this:
Screenshot 2022-10-29 at 3 01 24 PM
Apologies If I didn't make that clear earlier.

**Review by zeim839 — CHANGES_REQUESTED** [review]
Please add a section title and heading as below: 
Screenshot 2022-10-29 at 3 01 24 PM

Apologies If i didn't make that clear earlier.

**Comment by Brian-Magnuson** [comment]
Yeah sure, I can try working on that

**Comment by Brian-Magnuson** [comment]
image
I did my best to get the heading to look right. Notice that the font of 'ABOUT' is not quite the same as in the picture.

**Review by zeim839 — APPROVED** [review]

**Comment by zeim839** [comment]
Great work, I love the trapezoid box effect.

**Pull request merged**
