### PR TITLE
Updated admin page

### PR DESCRIPTION
**Pull request by RyanMachado**

### CODE REVIEW

**Comment by zeim839** [comment]
@willfpearce Could you implement the checkbox feature for the second table? Everything is located in the `views/admin.ejs` page for this PR. You can access the test route at `/test`

**Comment by willfpearce** [comment]
> @willfpearce Could you implement the checkbox feature for the second table? Everything is located in the `views/admin.ejs` page for this PR. You can access the test route at `/test`

👍

**Comment by willfpearce** [comment]
@zeim839 I don't think I can contribute to this existing pr without having write permissions. So I'll just copy the code and create a new request.

**Comment by willfpearce** [comment]
@zeim839 Should I remove the old /preview route?

**Comment by zeim839** [comment]
> @zeim839 I don't think I can contribute to this existing pr without having write permissions. So I'll just copy the code and create a new request.

Have you started? I can give you permissions if you haven't. 



> @zeim839 Should I remove the old /preview route?

No, just leave it for now.

**Comment by willfpearce** [comment]
> > @zeim839 I don't think I can contribute to this existing pr without having write permissions. So I'll just copy the code and create a new request.
> 
> Have you started? I can give you permissions if you haven't.
> 

I have started, but I cloned the PR branch through the github cli, so I can push directly to this PR if you give me permissions or I can push it to my fork.

**Review by zeim839 — APPROVED** [review]

**Comment by zeim839** [comment]
Great work, thanks everyone.

**Pull request merged**
