### PR TITLE
Make footer links open on in the new tab

### PR DESCRIPTION
**Pull request by Myrfion**

### CODE REVIEW

**Comment by Myrfion** [comment]
#57

**Review by zeim839 — APPROVED** [review]

**Comment by Myrfion** [comment]
Hi, could you please a the `hacktoberfest-accepted` label to my PR, because I want to use it for the hacktoberfest. Thank you

**Comment by Myrfion** [comment]
@zeim839

**Comment by zeim839** [comment]
Let me know if this is ok

**Pull request merged**
