### PR TITLE
Feat: Prettier add

### PR DESCRIPTION
**Pull request by vatsalsinghkv**
- Prettier added locally
- Npm script configured
- Prettier formatted files

### CODE REVIEW

**Review by zeim839 — CHANGES_REQUESTED** [review]
Would it be possible to revert changes to LICENSE.md and then configure the prettier package to ignore it? We want the license to remain unchanged.

**Comment by vatsalsinghkv** [comment]
umm sure you want me to ignore license.md  from prettier right?

**Comment by vatsalsinghkv** [comment]
I think I changed it.

**Review by zeim839 — CHANGES_REQUESTED** [review]
We need the prettier module to output 'error' when linting fails - this is because we use an automated CI script to notify us when pull requests fail. When the prettier module doesn't output failures, then we can't automatically fail CI tests. 

Please take a look at this page https://prettier.io/docs/en/integrating-with-linters.html

The output of the linter should look something like this:
```js
error: Insert `,` (prettier/prettier) at pkg/commons-atom/ActiveEditorRegistry.js:22:25:
  20 | import {
  21 |   observeActiveEditorsDebounced,
> 22 |   editorChangesDebounced
     |                         ^
  23 | } from './debounced';;
  24 |
  25 | import {observableFromSubscribeFunction} from '../commons-node/event';


error: Delete `;` (prettier/prettier) at pkg/commons-atom/ActiveEditorRegistry.js:23:21:
  21 |   observeActiveEditorsDebounced,
  22 |   editorChangesDebounced
> 23 | } from './debounced';;
     |                     ^
  24 |
  25 | import {observableFromSubscribeFunction} from '../commons-node/event';
  26 | import {cacheWhileSubscribed} from '../commons-node/observable';


2 errors found.
```

This is from a plugin that's documented here: https://github.com/prettier/eslint-plugin-prettier

**Comment by vatsalsinghkv** [comment]
I'm not sure if it's possible as prettier isn't working over .ejs files. The case with eslint and prettier is different as they both can format .js & .ts files but it's not the same with .ejs files as prettier not formatting .js & .ejs files

**Pull request closed without merging**
