### PR TITLE
fix : made navbar reponsive

### PR DESCRIPTION
**Pull request by amitanshusahu**
### 👁️  here is a video preview of the working have a look at 👇🏻 
[screen-recorder-sun-oct-16-2022-02-29-13.webm](https://user-images.githubusercontent.com/83657737/196007763-a99b8c4d-dce2-4144-aa04-340fb20dba60.webm)

😅  __sorry for the quality__

### CODE REVIEW

**Comment by amitanshusahu** [comment]
### Note:-
> the __hamburger menu icon__ you sent was blurry, so i didn't use it , instead i made a similar one using inkscape

**Comment by zeim839** [comment]
It's not working on my device. Are you sure you've committed all your changes? Only 1 file was changed.

**Comment by amitanshusahu** [comment]
Oh! Sorry..

**Comment by zeim839** [comment]
Great work, but the buttons are still clickable even when the menu is hidden.

**Comment by amitanshusahu** [comment]
OK , I will fix it..

**Comment by amitanshusahu** [comment]
Done now 😅

**Comment by zeim839** [comment]
Great work as always, thank you so much.

**Pull request merged**
