### PR TITLE
feat: navbar "become a member" button animation

### PR DESCRIPTION
**Pull request by willfpearce**
navbar_anim_1
some of the css can be combined with the item highlighting code

### CODE REVIEW

**Comment by zeim839** [comment]
Could you try these colors out and respond with a gif/video of how the animation looks?
Hex: #2AB6BC
Hex: #374BFE

@willfpearce

**Comment by willfpearce** [comment]
> Could you try these colors out and respond with a gif/video of how the animation looks?
> Hex: #2AB6BC
> Hex: #374BFE
> 
> @willfpearce 

👍👍

**Comment by willfpearce** [comment]
@zeim839 
navbar_highlighting_ttb
Alternate:
navbar_highlighting_btt

Personally, I like the turquoise to blue animation the best out of the four we've made (and prefer the turquoise accent color in general to the green)

**Comment by zeim839** [comment]
Could you also try green to turquoise & green to blue?

**Comment by willfpearce** [comment]
navbar_highlighting_ttg

**Comment by zeim839** [comment]
Lets go with this one:
https://user-images.githubusercontent.com/23342659/196827101-3252c6b7-90d4-48a6-8865-3b0146bba12d.gif

**Comment by willfpearce** [comment]
> Let's go with this one: https://user-images.githubusercontent.com/23342659/196827101-3252c6b7-90d4-48a6-8865-3b0146bba12d.gif

Done. Also changed the highlight color

**Pull request merged**
