### PR TITLE
blog: where is CSE A101?

### PR DESCRIPTION
**Pull request by zeim839**
Check it @danielwildsmith

### CODE REVIEW

**Review by danielwildsmith — CHANGES_REQUESTED** [review]
LGTM but can you add a meme please and thank you: https://tenor.com/search/shocked-face-meme-gifs

**Comment by danielwildsmith** [comment]
yeah this is brilliant

**Comment by danielwildsmith** [comment]
SEO osc style

**Comment by zeim839** [comment]
shocked_face_meme_green_screen_creatorset mp4_2023-01-27_03-57-29 901

**Let there be light.**

**Pull request merged**
