### PR TITLE
fix: landing page style tweaks

### PR DESCRIPTION
**Pull request by willfpearce**
fixes overflow issue on index and added some padding to footer

### CODE REVIEW

**Comment by willfpearce** [comment]
@zeim839 I don't know if it is just on my computer. But the problem is the footer extends further than the body for some reason causing the horizontal scroll bar to be visible, and you can scroll a little bit left to right. The overflow-x hidden wasn't a great solution so I tweaked the widths a little bit and removed the max-width 1400px inline style on the footer (I thought this would cause a problem but it actually works fine without it)

**Review by zeim839 — CHANGES_REQUESTED** [review]
Could you also add the footer to the admin page? Lets make it so that page body takes up the entirety of the page and the footer is at the bottom.

**Comment by willfpearce** [comment]
Ok, I made it so you have to scroll to see it

**Review by zeim839 — APPROVED** [review]
I've changed the dashboard-section min-height to:
```css
min-height: calc(100vh - 70px - 92.5px);
```
Where 70px is the height of the header and 92.5px is the height of the footer. This keeps the footer in place.

**Pull request merged**
